### ISSUE TITLE
CORS for Multiple Controllers?

### ISSUE THREAD

**Issue by elogicmedia** [snelg/cakephp-cors#12]
How do I go about adding CORS for multiple controllers?

Single works like this as per your example for me no worries:

DispatcherFactory::add('Cors.Cors', ['routes' => [
    'Employees'
]]);

HOWEVER trying this for multiple controlers doesn't? I guess this is wrong.

DispatcherFactory::add('Cors.Cors', ['routes' => [
    'Employees', 'LabourLevels'
]]);

Thanks

**Comment by snelg** [comment]
That should be the proper syntax. I just tried it myself with multiple controllers, and it worked properly:

``` php
DispatcherFactory::add('Cors.Cors', ['routes' => [
    'Members', 'Clubs', 'AuditDeltas'
]]);
```

I'm afraid I don't have any other specific debugging suggestions off the top of my head.

**Comment by elogicmedia** [comment]
Thanks for the reply, the issue ended up being within my cake app and not your plugin. Sorry about that.
