### ISSUE TITLE
Filter is deprecated

### ISSUE THREAD

**Issue by ozee31** [snelg/cakephp-cors#13]
Hi,

Your plugin use Filter but it's deprecated in cakephp 3.3.
I had not seen your plugin before and i created a plugin [here](https://github.com/ozee31/cakephp-cors) (use middleware)

We can work together to not have 2 different plugins

**Comment by snelg** [comment]
My plugin was written very quickly, and I do not even use it myself any more. I am fine with telling people to use yours instead if they use 3.3 or above :)

**Comment by ozee31** [comment]
yes you can write a message in your readme

**Comment by snelg** [comment]
Good idea. Done.

**Comment by ozee31** [comment]
think you

**Comment by dereuromark** [comment]
Both in composer json and in https://github.com/snelg/cakephp-cors/blob/master/composer.json you can mark it as abandoned, please do so for clarification.
